[build.environment]

NODE_VERSION = "12.16.1"
YARN_VERSION = "1.22.4"
NEXT_TELEMETRY_DISABLED = "1"
LISTING_SERVICE_URL = "https://listings.bloom.exygy.dev/"

[context.production.environment]
GTM_KEY = "GTM-W8LH9F9"

[context.branch-deploy.environment]
GTM_KEY = "GTM-KF22FJP"