# trunk-ignore-all(checkov/CKV2_GHA_1)
name: Public Cypress

on:
  pull_request:
    branches:
      - main
env:
  PORT: 3100
  # trunk-ignore(yamllint/quoted-strings)
  # trunk-ignore(checkov/CKV_SECRET_6)
  EMAIL_API_KEY: 'SOME-LONG-SECRET-KEY'
  # trunk-ignore(yamllint/quoted-strings)
  APP_SECRET: 'SOME-LONG-SECRET-KEY'
  CLOUDINARY_SECRET: CLOUDINARY_SECRET
  CLOUDINARY_KEY: CLOUDINARY_KEY
  PARTNERS_PORTAL_URL: http://localhost:3001
  # trunk-ignore(checkov/CKV_SECRET_4)
  DATABASE_URL: postgres://bloom-dev:bloom@127.0.0.1:5432/bloom
  TEST_DATABASE_URL: postgres://bloom-dev:bloom@127.0.0.1:5432/bloom_test
  BLOOM_API_BASE: https://api.housingbayarea.bloom.exygy.dev
  # trunk-ignore(yamllint/quoted-strings)
  BLOOM_LISTINGS_QUERY: "/fake"
  # trunk-ignore(yamllint/quoted-strings)
  JURISDICTION_NAME: 'Bay Area'
  BACKEND_API_BASE: http://localhost:3100
  LISTINGS_QUERY: /listings
  NEXTJS_PORT: 3000
  JURISDICTION_INCLUDE_LIST: San Jose,San Mateo,Alameda
  LISTING_VIEW: base
  JURISDICTION_ENDPOINT_PATH: /jurisdictions
  LISTINGS_ENDPOINT_PATH: /listings
  EXTERNAL_API_BASE: https://api.housingbayarea.bloom.exygy.dev
  MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
  DISABLE_CORS: "TRUE"
  LANGUAGES: en,es,zh,vi,tl
  NOTIFICATIONS_SIGN_UP_URL: http://example.com


jobs:
  public-cypress:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: bloom-dev
          POSTGRES_PASSWORD: bloom
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Check postgres
        # trunk-ignore(actionlint/expression)
        run: pg_isready -h 127.0.0.1 -p ${{ job.services.postgres.ports[5432] }}

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: yarn in root dir
        run: yarn

      - name: yarn in backend/core dir
        working-directory: ./backend/core
        run: yarn

      - name: Check postgres
        run: pg_isready -h 127.0.0.1 -p 5432

      - name: Create DB
        run: psql -U bloom-dev -c 'CREATE DATABASE bloom;'
        env:
          PGHOST: 127.0.0.1
          PGPASSWORD: bloom

      - name: Setup backend
        run: yarn test:backend:core:dbsetup
        env:
          PGHOST: 127.0.0.1
          PGPASSWORD: bloom
          PGUSER: bloom-dev

      - name: yarn in tasks/import-listings dir
        working-directory: ./tasks/import-listings
        run: yarn
      
      - name: Build import
        working-directory: ./tasks/import-listings
        run: yarn build

      - name: Import listings
        working-directory: ./tasks/import-listings
        run: yarn import:run:local:dev

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./sites/public
          build: yarn build
          start: yarn dev:listings, yarn start
          # trunk-ignore(yamllint/quoted-strings)
          wait-on: 'http://localhost:3100/jurisdictions'
          record: false # set this value to true to record videos in cypress cloud for debugging purposes - skip passing tests
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.PUBLIC_CYPRESS_RECORD_KEY }}

       