name: Infra CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/infra_ci.yml'
      - 'infra/**'

permissions:
  contents: read

jobs:
  check-tofu-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Check tofu fmt
        shell: bash
        run: |
          if ! docker container run --rm \
               -v ./infra:/infra \
               --workdir /infra \
               --entrypoint tofu \
               ghcr.io/${{ github.repository }}/infra-dev:gitbranch-main-latest \
               fmt -check -diff -recursive
          then
            echo 'ERROR: not all tofu files are correctly formatted'
            exit 1
          fi
