name: Backend Unit Tests

on:
  pull_request:
    branches:
      - main
env:
  APP_SECRET: 'SOME-LONG-SECRET-KEY'
  DATABASE_URL: postgres://bloom-dev:bloom@127.0.0.1:5432/bloom
  EMAIL_API_KEY: 'SG.SOME-LONG-SECRET-KEY'
  TWILIO_ACCOUNT_SID: 'AC.TEST'
  TWILIO_AUTH_TOKEN: 'TEST'
  MFA_CODE_VALID: '600000'
  MFA_CODE_LENGTH: 5
  AUTH_LOCK_LOGIN_COOLDOWN: '1800000'
  AUTH_LOCK_LOGIN_AFTER_FAILED_ATTEMPTS: '5'
  TWILIO_PHONE_NUMBER: '123456789'
  TIME_ZONE: America/Los_Angeles
  THROTTLE_TTL: 3600000
  THROTTLE_LIMIT: 100
  TEST_CONNECTION_STRING: postgres://bloom-dev:bloom@127.0.0.1:5432/bloom
  GOOGLE_API_KEY: "secret-key"
  GOOGLE_API_EMAIL: "secret-key"
  GOOGLE_API_ID: "secret-key"
  RECAPTCHA_KEY: "secret-key"
  GOOGLE_CLOUD_PROJECT_ID: "secret-key"
  LOTTERY_DAYS_TILL_EXPIRY: 45
  CLOUDINARY_CLOUD_NAME: "exygy"

jobs:
  backend-unit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22

      - name: yarn in api
        working-directory: ./api
        run: yarn

      # Tests
      - name: yarn unit test api
        working-directory: ./api
        run: yarn test
